spring:
  main:
    log-startup-info: true
  application:
    name: demo-task-sched-db

server:
  address: localhost
  port: 9910
  servlet:
    context-path: /demo/scheduler/api
    
logging:
  level:
    mike.bootstrap: INFO
    mike.demo: DEBUG
    web: INFO

springdoc:
  swagger-ui:
    enabled: true
    display-request-duration: true
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: list
